#!/usr/bin/env ansible-playbook
---

- hosts: localhost
  tasks:
    - name: Let's list all realms
      keycloak_list_realms:
        server_url: localhost:8888
        login: admin
        password: Pa55w0rd
      register: realms

    - debug: var=realms
